CREATE DATABASE ESCOLA;
USE ESCOLA;


CREATE TABLE ALUNO (
    ID INT AUTO_INCREMENT PRIMARY KEY,  
    NOME VARCHAR(255) NOT NULL,         
    EMAIL VARCHAR(255),                 
    TELEFONE VARCHAR(15)                
);


CREATE TABLE DISCIPLINA (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,  
    NOME VARCHAR(255) NOT NULL              
);


CREATE TABLE MATRICULA (
    ID INT AUTO_INCREMENT PRIMARY KEY,  
    ALUNO_ID INT NOT NULL,              
    DISCIPLINA_ID INT NOT NULL,         
    DATA_MATRICULA DATE NOT NULL,       
    FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID),  
    FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA(CODIGO)  
);

